### ISSUE TITLE
Axios dependency throwing "Critical Security Vulnerability" error on NPM install

### ISSUE THREAD

**Issue by sevilnatas** [MicahElliott/dbdoc#5]
When trying to install dbdocs with npm ('$ sudo npm install -g dbdocs'), npm throws the following warning:

`npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410`

**Comment by MicahElliott** [comment]
I think this is NPM picking up a different project called "dbdocs" (plural). You'll want to install this package according to https://github.com/MicahElliott/dbdoc#installation
